# Generated by Django 3.2.25 on 2024-10-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ('created_at',), 'verbose_name': 'Music', 'verbose_name_plural': 'Musics'},
        ),
        migrations.AlterField(
            model_name='music',
            name='img',
            field=models.ImageField(upload_to='music_image'),
        ),
        migrations.AddIndex(
            model_name='music',
            index=models.Index(fields=['code'], name='music_music_code_e50db1_idx'),
        ),
    ]
