# Generated by Django 5.1.2 on 2024-10-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_dailyvisit_dailyurlvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('url', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('visit_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('date', 'url', 'ip_address')},
            },
        ),
        migrations.DeleteModel(
            name='DailyURLVisit',
        ),
        migrations.DeleteModel(
            name='DailyVisit',
        ),
    ]
